# Generated by Django 3.2.6 on 2021-09-01 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addmission', '0002_alter_addmission_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('cash', 'cash'), ('cheque', 'cheque'), ('neft', 'neft')], max_length=25)),
                ('amount', models.IntegerField()),
                ('bank_name', models.CharField(blank=True, max_length=40, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=40, null=True)),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('cheque_no', models.CharField(blank=True, max_length=50, null=True)),
                ('ref_id', models.CharField(blank=True, max_length=40, null=True)),
                ('addmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='addmission.addmission')),
            ],
        ),
    ]
