# Generated by Django 3.2.6 on 2021-08-20 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('Fees', models.IntegerField()),
                ('no_of_days', models.IntegerField()),
                ('remarks', models.TextField()),
                ('pending_fees', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='course.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addmission', to='student.student')),
            ],
        ),
    ]
