# Generated by Django 3.2.6 on 2021-08-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('father_first_name', models.CharField(max_length=50)),
                ('father_last_name', models.CharField(max_length=50)),
                ('father_middle_name', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=200)),
                ('areaname', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('phno1', models.CharField(max_length=10)),
                ('phno2', models.CharField(max_length=10)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('emailid', models.EmailField(max_length=254)),
            ],
        ),
    ]
