# Generated by Django 3.2.7 on 2021-09-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='student_photo/'),
        ),
    ]
